use_frameworks!

platform :ios, '10.0'

def util_pods
  pod 'Then'
end

def di_pods
  pod 'Swinject'
end

def network_pods
  # 대표적인 네트워크 라이브러리입니다.
  pod 'Alamofire'
end

# Pods for RxSwift+MVVM
def rx_swift_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'RxOptional'
  pod 'RxViewController'
end

target 'iamport-ios_Example' do

  # cocoapods 사용시 enable
  # cocoapods 사용시 enable
  # pod 'iamport-ios', :path => '../' # local
  # pod 'iamport-ios', '~> 1.1.0' # remote
  # cocoapods 사용시 enable
  # cocoapods 사용시 enable

  use_frameworks!

  di_pods
  network_pods
  util_pods
  # rx_swift_pods

  target 'iamport-ios_Tests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
